# Stage 1: Build the Go binary
FROM golang:1.19-alpine AS builder

WORKDIR /app

COPY . .

RUN go build -o app

# Stage 2: Create a minimal image for the final app
FROM alpine:latest

WORKDIR /app

# RUN apk update && apk add subversion --no-cache
# RUN mkdir files

COPY --from=builder /app/app .

EXPOSE 8083

CMD ["./app"]