version: "3"


volumes:
  minio-data:

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=yale918
      - MINIO_ROOT_PASSWORD=12345678
    volumes:
      - minio-data:/data
    networks:
      - nginx